#!/usr/bin/env node
// Prototype: vercel-labs/skills  src/agents.ts  ->  agents.toml
// Regex block-parser. No deps, no TS eval. Reports anything non-uniform so
// the 5% that needs hand-porting is loud, not silent.
import { readFileSync, writeFileSync } from 'node:fs';

const src = readFileSync(process.argv[2] ?? 'agents.ts', 'utf-8');
const OUT_PATH = process.argv[3] ?? 'agents.toml';

// 1. home-var declarations -> template. `${ENV:-fallback}` shell-style so a
//    human reads it; Rust side splits on `:-`.
const HOMEVARS = {
  home: '~',
  configHome: '${XDG_CONFIG_HOME:-~/.config}',
  codexHome: '${CODEX_HOME:-~/.codex}',
  claudeHome: '${CLAUDE_CONFIG_DIR:-~/.claude}',
  vibeHome: '${VIBE_HOME:-~/.vibe}',
  hermesHome: '${HERMES_HOME:-~/.hermes}',
  autohandHome: '${AUTOHAND_HOME:-~/.autohand}',
  zedAppDataHome: '${APPDATA}',
  zedFlatpakConfigHome: '${FLATPAK_XDG_CONFIG_HOME}',
};

// Hand-ports: agents whose detect isn't a uniform OR-of-existsSync(path).
// zcode = pure OR-paths (expressible). eve = AND + package.json dep check
// (not expressible as paths) -> flagged special, consumer treats as explicit-only.
const OVERRIDE = {
  zcode: { detect: ['~/.zcode', '/Applications/ZCode.app'] },
  eve: { detect: [], detect_special: 'eve' },
};

const unhandled = [];

// join(VAR, 'a', 'b')  ->  template + '/a/b'.  Bare home-var -> template.
// Bare string literal -> as-is.  process.cwd() base -> './...'.
function normPath(expr, ctx) {
  expr = expr.trim();
  if (HOMEVARS[expr]) return HOMEVARS[expr]; // bare var: existsSync(claudeHome)
  let m = expr.match(/^join\(\s*(\w+|process\.cwd\(\))\s*,\s*(.+)\)$/);
  if (m) {
    const base = m[1] === 'process.cwd()' ? '.' : HOMEVARS[m[1]];
    if (base) {
      const parts = [...m[2].matchAll(/['"]([^'"]+)['"]/g)].map((x) => x[1]);
      if (parts.length) return `${base}/${parts.join('/')}`;
    }
  }
  m = expr.match(/^['"]([^'"]+)['"]$/); // bare literal e.g. '/Applications/ZCode.app'
  if (m) return m[1];
  unhandled.push(`${ctx}: ${expr}`);
  return null;
}

// 2. slice the `export const agents = { ... }` object body
const start = src.indexOf('export const agents');
const objStart = src.indexOf('{', start);
const body = src.slice(objStart + 1);

// 3. walk top-level agent entries by brace depth
const agents = {};
let i = 0;
while (i < body.length) {
  // match a key:  'aider-desk': {   or   amp: {
  const keyMatch = body.slice(i).match(/^\s*(?:'([^']+)'|"([^"]+)"|([\w-]+))\s*:\s*\{/);
  if (!keyMatch) {
    if (body[i] === '}') break; // end of agents object
    i++;
    continue;
  }
  const key = keyMatch[1] || keyMatch[2] || keyMatch[3];
  i += keyMatch[0].length;
  // capture this block by brace depth
  let depth = 1, blockStart = i;
  while (i < body.length && depth > 0) {
    if (body[i] === '{') depth++;
    else if (body[i] === '}') depth--;
    i++;
  }
  const block = body.slice(blockStart, i - 1);
  agents[key] = parseBlock(key, block);
}

function parseBlock(key, block) {
  const str = (f) => {
    const m = block.match(new RegExp(`${f}:\\s*'([^']*)'`));
    return m ? m[1] : null;
  };
  const out = { name: str('name') ?? key, displayName: str('displayName') };
  out.project = str('skillsDir');

  // globalSkillsDir
  const g = block.match(/globalSkillsDir:\s*([^\n]+?),\s*(?:\n|$)/);
  const gexpr = g ? g[1].trim() : 'undefined';
  if (gexpr === 'undefined') out.global = null;
  else if (/^\w+\(\)$/.test(gexpr)) { out.global = null; out.global_special = gexpr.replace(/\(\)$/, ''); }
  else out.global = normPath(gexpr, `${key}.global`);

  // detectInstalled: pull every existsSync(...) arg
  const det = block.match(/detectInstalled:\s*async[\s\S]*?\{([\s\S]*?)\n\s{4}\}/);
  out.detect = [];
  if (det) {
    for (const dm of det[1].matchAll(/existsSync\(([\s\S]*?)\)\s*(?:\|\||\)|;|$)/g)) {
      // dm[1] may itself contain join(...) with its own parens
      let arg = dm[1].trim();
      // re-attach a closing paren if it was a join(...)
      if (arg.startsWith('join(') && !arg.endsWith(')')) arg += ')';
      const p = normPath(arg, `${key}.detect`);
      if (p) out.detect.push(p);
    }
    if (/=>\s*false/.test(det[1])) out.detect_special = 'never';
    // catch non-existsSync detection (e.g. isZCodeInstalled(), pkg-json checks)
    if (!out.detect.length && !out.detect_special)
      unhandled.push(`${key}.detect: <non-uniform, hand-port>`);
  }
  if (OVERRIDE[key]) Object.assign(out, OVERRIDE[key]);
  return out;
}

// 4. emit TOML
function toml(o) {
  let s =
    '# GENERATED by scripts/sync-agents from vercel-labs/skills src/agents.ts.\n' +
    '# Do not edit by hand — run scripts/sync-agents/sync.sh to regenerate.\n\n';
  for (const [k, a] of Object.entries(o)) {
    s += `\n[agents."${k}"]\n`;
    s += `display_name = ${JSON.stringify(a.displayName)}\n`;
    s += `project = ${JSON.stringify(a.project)}\n`;
    if (a.global) s += `global = ${JSON.stringify(a.global)}\n`;
    if (a.global_special) s += `global_special = ${JSON.stringify(a.global_special)}\n`;
    if (a.detect && a.detect.length) s += `detect = ${JSON.stringify(a.detect)}\n`;
    if (a.detect_special) s += `detect_special = ${JSON.stringify(a.detect_special)}\n`;
  }
  return s.trimStart();
}

const out = toml(agents);
writeFileSync(OUT_PATH, out);

// 5. report
const n = Object.keys(agents).length;
// drop report lines for agents we hand-ported via OVERRIDE
const stillUnhandled = unhandled.filter((u) => !Object.keys(OVERRIDE).some((k) => u.startsWith(k + '.')));
console.log(`parsed ${n} agents -> agents.toml (${out.length} bytes)`);
console.log(`hand-ported via OVERRIDE: ${Object.keys(OVERRIDE).join(', ')}`);
console.log(`unhandled / still needs attention: ${stillUnhandled.length}`);
for (const u of stillUnhandled) console.log('  ! ' + u);

// self-check: fail loud if the parser silently broke
const cc = agents['claude-code'];
console.assert(n > 60, `expected >60 agents, got ${n}`);
console.assert(cc && cc.project === '.claude/skills', 'claude-code project path wrong');
console.assert(cc.global === '${CLAUDE_CONFIG_DIR:-~/.claude}/skills', `claude-code global wrong: ${cc.global}`);
console.assert(cc.detect[0] === '${CLAUDE_CONFIG_DIR:-~/.claude}', `claude-code detect wrong: ${cc.detect[0]}`);
console.log('self-check: claude-code OK');
